###登录信息
POST {{administrator_host}}/administrator/user/login
Content-Type: application/json

{
    "username": "20210000",
    "password": "123456"
}

###重试登录
POST http://123.56.248.217:63000/administrator/user/login
Content-Type: application/json

{
    "username": "20210000",
    "password": "123456"
}


###分页搜索查询小孩
GET {{administrator_host}}/administrator/user/search
Content-Type: application/json

{
  "page": "1",
  "size": "5",
  "name": "chenyucy"
}

###新增小孩
PUT {{administrator_host}}/administrator/user/save
Content-Type: application/json

{
  "id": "4",
  "username": "20210004",
  "score": "100",
  "password": "123456",
  "name": "cycy",
  "grade": "D",
  "locate": "b504",
  "duty": "4",
  "completed_tasks": "2"
}

###修改小孩
PUT {{administrator_host}}/administrator/user/save
Content-Type: application/json

{
  "id": "4",
  "name": "chenyucy",
  "grade": "D"

}





